server:
  port: 8013

spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.31.253:8848
        namespace: nacos-test
